spring.datasource.url=jdbc:h2:mem:kitchensink-quickstart;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
logging.file.name=kitchensink.log
logging.file.path=/Users/marcosordi/Documents/mongodb/kitchensinkh2/kitchensink
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.xhtml
server.error.whitelabel.enabled=false
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.org.jboss.as.quickstarts=DEBUG